version: "2.0"
services:
  spotexchange:
    build: .
    ports:
      - "8888:8888"
    env_file:
      - .env
  mongodb:
    #image: sinenomine/mongodb-s390x  #for IBM Z
    image: mongo:latest #local dev
    ports:
      - "27017:27017"
    #volumes:
    #  - /opt/mongodb:/data/db
