version: "2.0"
services:
  spotexchange:
    build: .
    ports:
      - "8888:8888"
    env_file:
      - .env
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /opt/mongodb:/data/db
